### ISSUE TITLE
Multiple TRUE imports

### ISSUE THREAD

**Issue by nabijaczleweli** [jeaye/ncurses-rs#103] opened 2015-12-20 00:37 UTC
```
    Updating git repository `https://github.com/jeaye/ncurses-rs.git`
   Compiling ncurses v5.80.0 (https://github.com/jeaye/ncurses-rs.git#2b3e818d)
D:\Users\nabijaczleweli\.cargo\git\checkouts\ncurses-rs-a39bc38240b97745\master\src\menu\wrapper.rs:11:5: 11:20 error: a value named `TRUE` has already been imported in this module [E0252]
D:\Users\nabijaczleweli\.cargo\git\checkouts\ncurses-rs-a39bc38240b97745\master\src\menu\wrapper.rs:11 use constants::TRUE;
                                                                                                           ^~~~~~~~~~~~~~~
D:\Users\nabijaczleweli\.cargo\git\checkouts\ncurses-rs-a39bc38240b97745\master\src\menu\wrapper.rs:11:5: 11:20 help: run `rustc --explain E0252` to see a detailed explanation
D:\Users\nabijaczleweli\.cargo\git\checkouts\ncurses-rs-a39bc38240b97745\master\src\menu\wrapper.rs:8:1: 8:13 note: previous import of `TRUE` here
D:\Users\nabijaczleweli\.cargo\git\checkouts\ncurses-rs-a39bc38240b97745\master\src\menu\wrapper.rs:8 use libc::*;
                                                                                                      ^~~~~~~~~~~~
error: aborting due to previous error
Could not compile `ncurses`.
```
Happens on Rust stable 1.5.0, upstream `ncurses-rs`.

**Comment by nabijaczleweli** [comment] 2016-08-29 22:02
Any updates on this?

**Comment by jeaye** [comment] 2016-09-16 05:06
Sorry for the terribly long delay; I haven't been able to reproduce this, but I'm on Rust `1.11.0`. Since it's quite old and doesn't show up in the latest version, I'll close this for now.

I really appreciate you opening this ticket and I apologize for not replying sooner.

**Closed by jeaye** 2016-09-16 05:06 UTC

**Comment by nabijaczleweli** [comment] 2016-09-16 06:15
Yeah, this particular error can no longer be reproduced (latest stable, upstream `ncurses-rs`), which is not to be said about a shitton of type errors
